name: Create a Tag on Pull Request merged in main

on:
  pull_request:
    types:
      - closed
    branches: [ "main" ]

jobs:

  create-tag:
    if: github.event.pull_request.merged && github.ref_type != 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Push tag with source branch name
        uses: mathieudutour/github-tag-action@v6.1 # https://github.com/mathieudutour/github-tag-action
        with:
          custom_tag: ${{ github.head_ref }}  
          github_token: ${{ secrets.GITHUB_TOKEN }}

